---

- name: Install Python3 virtual environment
  hosts:  all
  become: yes

  tasks:
  - name: Install virtual environment
    package:
      name: 
      - Python3
      - python3.8-venv
      - Python3-pip
    state: present
    update_cache: yes
    #when: ansible_distribution == "Ubuntu"

  - name: install flask with pip
    pip: 
      name: flask
      state: present
#    when: ansible_distribution == "Ubuntu"

  # ⁃ name: enable flask
  #   File:
  #   ⁃ Opt/flask-app
  # State: present
  
  - name: Install Git
    yum:
      name: git
    when: ansible_distribution == "centos"

...